### ISSUE TITLE
[API] The client crashes in API 23

### ISSUE THREAD

**Issue by hyun-chung** [thedeconstructors/Krono#31]
The minimum API no longer known

**Comment by jihyukchung** [comment]
The issue is coming from picasso

**Comment by Mikesteam1234** [comment]
Is the issue that clients 23 and lower are no longer able to run the application?

**Comment by jihyukchung** [comment]
> Is the issue that clients 23 and lower are no longer able to run the application?

Yes, it isn't a big problem. We just need to try another approach or just update the minimum API level.

**Comment by hyun-chung** [comment]
It only causes the application to crash the first time for some reason.

**Comment by Mikesteam1234** [comment]
Fixed through changing to min version api 24 :)

**Comment by hyun-chung** [comment]
Seems to be working in 23 as well. I'll keep testing around 20+
