### ISSUE TITLE
[Facebook Login] Facebook Server Infinite Loop

### ISSUE THREAD

**Issue by hyun-chung** [thedeconstructors/Krono#43]
The initial access was successful. This is most likely due to the app not deployed to the Playstore. The Facebook for Developers needs the access to the class name.

**Comment by jihyukchung** [comment]
Disabled the button

**Comment by hyun-chung** [comment]
Fixed [https://github.com/thedeconstructors/Krono/commit/39a662404cbf2847bddc0bf7bc3175db159b926b](url)
