### ISSUE TITLE
Login issue - While loading

### ISSUE THREAD

**Issue by Mikesteam1234** [thedeconstructors/Krono#8]
Problem:
Currently once a user has selected the login as user option, and the loading symbol is being displayed, it is still possible to select the skip option. Once the skip option has been chosen, you are logged in as the user and then taken to the "unknown user".

Expected Behavior:
Upon selecting login, or skip and the loading symbol is displayed no other option should be selected or processed until the user has been logged in.

Steps to reproduce:
1. Build the app
2. Select Login
3. Select Login again
4. Select skip right after

Note on difficulty of reproduction, attempt turning off the internet first to delay the log in process.

**Comment by jihyukchung** [comment]
I was able to replicate the issue, and it's fixed in [my branch](https://github.com/thedeconstructors/Krono/commit/8a3e9531693b29cdafd81dc5324f1a4bb0ddb5d6).
